---
name: tarpaulin
on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin
      - run: >-
          cargo tarpaulin --out Xml --all-features
          --exclude-files src/lib.rs -- --test-threads 1
      - uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
